### ISSUE TITLE
Identify Real World Examples of Design Patterns

### ISSUE THREAD

**Issue by sneha-thomas1** [nguyensjsu/fa18-202-brainy-amigos#3]

**Comment by AkshayPagar** [comment]
**Composite Pattern:**
1. Russian Doll: The Russian doll is an excellent example of composite pattern. Russian doll is a set of wooden dolls of decreasing size placed one inside another. This represents composite pattern. 

2. Burger Making: As per our lab2 and lab7, there is a composite pattern associated with assembling the burger assuming the base ingredients as leaf nodes. We can visualize a kitchen counter and assemble the burger from the ingredients placed on the counter.

3.  Family Tree: Family tree is a very good example of composite pattern as it describes hierarchy. Every node can be a leaf or container in family. We can visualize a family picture in game and after clicking the picture we can show the hierarchy for family.

These are examples I came up with for real-world scenarios for composite pattern.

**Comment by bargemb** [comment]
### Adaptor Pattern

1. Power plug and sockets in different countries
2. Fit square peg into round hole
3. Charging different devices using different plugs
4. Card reader acting as adaptor between memory card and laptop([link](https://www.tutorialspoint.com/design_pattern/adapter_pattern.htm))
5. Make audio player play unsupported formats([link](https://www.tutorialspoint.com/design_pattern/adapter_pattern.htm))
